//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/_ML/Engine/Input/CommomInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace ML.Engine.Input
{
    public partial class @CommomInput: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @CommomInput()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""CommomInput"",
    ""maps"": [
        {
            ""name"": ""Common"",
            ""id"": ""7f866e33-da0f-46d4-9574-607634f09ada"",
            ""actions"": [
                {
                    ""name"": ""Confirm"",
                    ""type"": ""Button"",
                    ""id"": ""3b005375-d1a3-4413-91d0-31adb0879d8b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RT"",
                    ""type"": ""Button"",
                    ""id"": ""025a32f2-1551-4d1d-9883-0709b8ad78b4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ConfirmHold"",
                    ""type"": ""Button"",
                    ""id"": ""943f1d23-9cf7-4f06-9a2e-13064a30fde5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwichBtn"",
                    ""type"": ""Value"",
                    ""id"": ""a86454bc-c2e4-484f-8224-919690d1e274"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TurnPage"",
                    ""type"": ""Value"",
                    ""id"": ""c329d0d8-d613-4e9a-8e26-ac645f7f712b"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""09cef832-34f8-464e-8f2b-224e1c2034db"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NextTerm"",
                    ""type"": ""Button"",
                    ""id"": ""76ef039b-0a7a-48b5-995a-585f282f741c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LastTerm"",
                    ""type"": ""Button"",
                    ""id"": ""ee2967d4-6afd-4b4f-a006-ce4b4956bfec"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MainInteract"",
                    ""type"": ""Button"",
                    ""id"": ""4d85639f-8f55-4c71-955b-d62bf03bbd82"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MainInteractHold"",
                    ""type"": ""Button"",
                    ""id"": ""8c55ffc6-06aa-4643-be06-87afc6fad4bf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SubInteract"",
                    ""type"": ""Button"",
                    ""id"": ""420ccfdc-bc41-450b-89b4-4ddd37420e68"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SubInteractHold"",
                    ""type"": ""Button"",
                    ""id"": ""1a60b90a-4b60-407e-b29f-5158576d18f4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""380f7fa1-f483-4987-a17c-3827a5fcb70c"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9689dff5-f141-4dfe-8ddc-542391c65d9d"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dde9783f-58d9-4638-b426-18c22a02e9e1"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""53c908d5-5dce-46da-bf16-c528f2132276"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""KeyBoard"",
                    ""id"": ""82d4d19e-5b30-4f0d-8028-9f745500ec3e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c9bbb5a0-94e3-409c-96ee-dbc53b519683"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ec454c15-3627-4d8b-bb9c-9b33d123931b"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""6522029b-21c8-4cea-977a-a88cd81affba"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""34c7dc56-dd10-4fa6-afe4-9a44e386614d"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""XBOX"",
                    ""id"": ""b6f4ad35-aa09-4186-a0e6-c66060ea1f2c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""018b9edb-1e37-4011-859b-20b139c25f5e"",
                    ""path"": ""<XInputController>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9c0e7962-370e-4e47-9cab-ae06fd050801"",
                    ""path"": ""<XInputController>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""28ba3262-97c5-4967-90de-fe81e1c22de5"",
                    ""path"": ""<XInputController>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""8d897183-7f8e-4124-a122-55796b99b7ad"",
                    ""path"": ""<XInputController>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""858a8040-3508-4ba6-a6ba-2bc3479924f5"",
                    ""path"": ""<XInputController>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextTerm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""03c436fc-68c9-42da-ac22-610b88744e3b"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextTerm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1268ff3-c630-4b18-b70b-3383c9661077"",
                    ""path"": ""<XInputController>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LastTerm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""19c0683d-bd06-4878-9217-f8baa8cede63"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LastTerm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd370cd5-fc50-4ca9-8763-ab094b11d38a"",
                    ""path"": ""<XInputController>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MainInteract"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""22286a56-fbc5-4350-bcd2-2a302f42443d"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MainInteract"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8bc1fc65-2cf2-451b-bad1-e02fbd1cdf25"",
                    ""path"": ""<XInputController>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SubInteract"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""38f6b071-66c9-4780-a859-2f66a932762c"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SubInteract"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41f83e4e-349f-4c5b-bbb2-57d9ced70a81"",
                    ""path"": ""<XInputController>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MainInteractHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5aae12d7-d95c-4e04-8407-6b0a9c5d5548"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MainInteractHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""50fc1a45-96e0-4454-9f1e-883134fb8153"",
                    ""path"": ""<XInputController>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SubInteractHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dc02504a-6cbb-4c1f-903e-70914b6731c8"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SubInteractHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab5b778b-20a8-4c4e-b254-5b58269d3858"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ConfirmHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f85ca303-9314-4d36-8d79-fd22cf0bf766"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ConfirmHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0c68dd69-c617-4614-8b08-14daf51c6e9a"",
                    ""path"": ""<XInputController>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""48b3299d-64f3-4eba-b3ac-bcf4b7267a3c"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""XBOX"",
                    ""id"": ""0bb1464c-9820-4360-9abf-a75409463ea9"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TurnPage"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""57ffd815-238b-45d6-b03d-cf7cb3d13628"",
                    ""path"": ""<XInputController>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TurnPage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""2416eabe-543b-4af5-8dda-44ec64ca4c67"",
                    ""path"": ""<XInputController>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TurnPage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d22d5c01-ca9d-4257-acc1-d3f0bab06207"",
                    ""path"": ""<XInputController>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TurnPage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""5d9ba7de-45d2-4138-823e-ea1ac49c600c"",
                    ""path"": ""<XInputController>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TurnPage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""StartMenu"",
            ""id"": ""e78faf79-61ff-4aa7-9146-7a172679e32f"",
            ""actions"": [
                {
                    ""name"": ""SwichBtn"",
                    ""type"": ""Value"",
                    ""id"": ""494e2f86-7710-441e-833a-6464f6b2b25c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""KeyBoard"",
                    ""id"": ""a211c9b0-0fba-4a28-a3e5-e4128642b797"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""361ae183-da8c-4e50-adef-086f99a04432"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""364684de-ce04-4f46-86d2-9ba52ea58c76"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a3ed8003-098d-4c53-ade2-768d68fa8fde"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""062fb8f0-1c55-4c94-bfb5-49ba2f96c844"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""XBOX"",
                    ""id"": ""cc97dda1-f207-49e2-b095-8146cbbf4b49"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""84c8a198-84e4-469e-8d98-9d054a6b3430"",
                    ""path"": ""<XInputController>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e48ad3b3-6b8c-40e4-bc59-8ccb2142d381"",
                    ""path"": ""<XInputController>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b3d4b36f-5631-4d08-9b4b-58f869970754"",
                    ""path"": ""<XInputController>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""dfe97926-a7f4-4ccc-a230-c656b660ae98"",
                    ""path"": ""<XInputController>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""Option"",
            ""id"": ""59dd38bc-4fa4-4454-b3ee-406519cf2987"",
            ""actions"": [
                {
                    ""name"": ""SwichBtn"",
                    ""type"": ""Value"",
                    ""id"": ""ea6bfa20-4ae4-42ba-9b8f-782e06470c05"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""KeyBoard"",
                    ""id"": ""d1423c03-ce1e-4ac4-8bdf-0c76eaa61d73"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""324f7f9c-040f-4b70-9005-c77f11deea0c"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b60c8e68-a90d-42b2-8848-56cd0f3ad975"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""5e4d293f-b815-49f2-9bdb-870aa1f36bad"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c7db456c-5b6b-4740-b9c9-44c9dd3b0a08"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""XBOX"",
                    ""id"": ""a1062fd6-2dd8-4676-b575-36d22196fed9"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""7df6f870-1300-42a9-86bc-4ebbe4f8e168"",
                    ""path"": ""<XInputController>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""374809fa-49ee-44b8-886a-4957688cbe00"",
                    ""path"": ""<XInputController>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""7afcaf99-8f9f-4e70-84f7-71f6c978709e"",
                    ""path"": ""<XInputController>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""8d87755a-374e-40c7-97e4-4c9a2573b757"",
                    ""path"": ""<XInputController>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Common
            m_Common = asset.FindActionMap("Common", throwIfNotFound: true);
            m_Common_Confirm = m_Common.FindAction("Confirm", throwIfNotFound: true);
            m_Common_RT = m_Common.FindAction("RT", throwIfNotFound: true);
            m_Common_ConfirmHold = m_Common.FindAction("ConfirmHold", throwIfNotFound: true);
            m_Common_SwichBtn = m_Common.FindAction("SwichBtn", throwIfNotFound: true);
            m_Common_TurnPage = m_Common.FindAction("TurnPage", throwIfNotFound: true);
            m_Common_Back = m_Common.FindAction("Back", throwIfNotFound: true);
            m_Common_NextTerm = m_Common.FindAction("NextTerm", throwIfNotFound: true);
            m_Common_LastTerm = m_Common.FindAction("LastTerm", throwIfNotFound: true);
            m_Common_MainInteract = m_Common.FindAction("MainInteract", throwIfNotFound: true);
            m_Common_MainInteractHold = m_Common.FindAction("MainInteractHold", throwIfNotFound: true);
            m_Common_SubInteract = m_Common.FindAction("SubInteract", throwIfNotFound: true);
            m_Common_SubInteractHold = m_Common.FindAction("SubInteractHold", throwIfNotFound: true);
            // StartMenu
            m_StartMenu = asset.FindActionMap("StartMenu", throwIfNotFound: true);
            m_StartMenu_SwichBtn = m_StartMenu.FindAction("SwichBtn", throwIfNotFound: true);
            // Option
            m_Option = asset.FindActionMap("Option", throwIfNotFound: true);
            m_Option_SwichBtn = m_Option.FindAction("SwichBtn", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Common
        private readonly InputActionMap m_Common;
        private List<ICommonActions> m_CommonActionsCallbackInterfaces = new List<ICommonActions>();
        private readonly InputAction m_Common_Confirm;
        private readonly InputAction m_Common_RT;
        private readonly InputAction m_Common_ConfirmHold;
        private readonly InputAction m_Common_SwichBtn;
        private readonly InputAction m_Common_TurnPage;
        private readonly InputAction m_Common_Back;
        private readonly InputAction m_Common_NextTerm;
        private readonly InputAction m_Common_LastTerm;
        private readonly InputAction m_Common_MainInteract;
        private readonly InputAction m_Common_MainInteractHold;
        private readonly InputAction m_Common_SubInteract;
        private readonly InputAction m_Common_SubInteractHold;
        public struct CommonActions
        {
            private @CommomInput m_Wrapper;
            public CommonActions(@CommomInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @Confirm => m_Wrapper.m_Common_Confirm;
            public InputAction @RT => m_Wrapper.m_Common_RT;
            public InputAction @ConfirmHold => m_Wrapper.m_Common_ConfirmHold;
            public InputAction @SwichBtn => m_Wrapper.m_Common_SwichBtn;
            public InputAction @TurnPage => m_Wrapper.m_Common_TurnPage;
            public InputAction @Back => m_Wrapper.m_Common_Back;
            public InputAction @NextTerm => m_Wrapper.m_Common_NextTerm;
            public InputAction @LastTerm => m_Wrapper.m_Common_LastTerm;
            public InputAction @MainInteract => m_Wrapper.m_Common_MainInteract;
            public InputAction @MainInteractHold => m_Wrapper.m_Common_MainInteractHold;
            public InputAction @SubInteract => m_Wrapper.m_Common_SubInteract;
            public InputAction @SubInteractHold => m_Wrapper.m_Common_SubInteractHold;
            public InputActionMap Get() { return m_Wrapper.m_Common; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(CommonActions set) { return set.Get(); }
            public void AddCallbacks(ICommonActions instance)
            {
                if (instance == null || m_Wrapper.m_CommonActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_CommonActionsCallbackInterfaces.Add(instance);
                @Confirm.started += instance.OnConfirm;
                @Confirm.performed += instance.OnConfirm;
                @Confirm.canceled += instance.OnConfirm;
                @RT.started += instance.OnRT;
                @RT.performed += instance.OnRT;
                @RT.canceled += instance.OnRT;
                @ConfirmHold.started += instance.OnConfirmHold;
                @ConfirmHold.performed += instance.OnConfirmHold;
                @ConfirmHold.canceled += instance.OnConfirmHold;
                @SwichBtn.started += instance.OnSwichBtn;
                @SwichBtn.performed += instance.OnSwichBtn;
                @SwichBtn.canceled += instance.OnSwichBtn;
                @TurnPage.started += instance.OnTurnPage;
                @TurnPage.performed += instance.OnTurnPage;
                @TurnPage.canceled += instance.OnTurnPage;
                @Back.started += instance.OnBack;
                @Back.performed += instance.OnBack;
                @Back.canceled += instance.OnBack;
                @NextTerm.started += instance.OnNextTerm;
                @NextTerm.performed += instance.OnNextTerm;
                @NextTerm.canceled += instance.OnNextTerm;
                @LastTerm.started += instance.OnLastTerm;
                @LastTerm.performed += instance.OnLastTerm;
                @LastTerm.canceled += instance.OnLastTerm;
                @MainInteract.started += instance.OnMainInteract;
                @MainInteract.performed += instance.OnMainInteract;
                @MainInteract.canceled += instance.OnMainInteract;
                @MainInteractHold.started += instance.OnMainInteractHold;
                @MainInteractHold.performed += instance.OnMainInteractHold;
                @MainInteractHold.canceled += instance.OnMainInteractHold;
                @SubInteract.started += instance.OnSubInteract;
                @SubInteract.performed += instance.OnSubInteract;
                @SubInteract.canceled += instance.OnSubInteract;
                @SubInteractHold.started += instance.OnSubInteractHold;
                @SubInteractHold.performed += instance.OnSubInteractHold;
                @SubInteractHold.canceled += instance.OnSubInteractHold;
            }

            private void UnregisterCallbacks(ICommonActions instance)
            {
                @Confirm.started -= instance.OnConfirm;
                @Confirm.performed -= instance.OnConfirm;
                @Confirm.canceled -= instance.OnConfirm;
                @RT.started -= instance.OnRT;
                @RT.performed -= instance.OnRT;
                @RT.canceled -= instance.OnRT;
                @ConfirmHold.started -= instance.OnConfirmHold;
                @ConfirmHold.performed -= instance.OnConfirmHold;
                @ConfirmHold.canceled -= instance.OnConfirmHold;
                @SwichBtn.started -= instance.OnSwichBtn;
                @SwichBtn.performed -= instance.OnSwichBtn;
                @SwichBtn.canceled -= instance.OnSwichBtn;
                @TurnPage.started -= instance.OnTurnPage;
                @TurnPage.performed -= instance.OnTurnPage;
                @TurnPage.canceled -= instance.OnTurnPage;
                @Back.started -= instance.OnBack;
                @Back.performed -= instance.OnBack;
                @Back.canceled -= instance.OnBack;
                @NextTerm.started -= instance.OnNextTerm;
                @NextTerm.performed -= instance.OnNextTerm;
                @NextTerm.canceled -= instance.OnNextTerm;
                @LastTerm.started -= instance.OnLastTerm;
                @LastTerm.performed -= instance.OnLastTerm;
                @LastTerm.canceled -= instance.OnLastTerm;
                @MainInteract.started -= instance.OnMainInteract;
                @MainInteract.performed -= instance.OnMainInteract;
                @MainInteract.canceled -= instance.OnMainInteract;
                @MainInteractHold.started -= instance.OnMainInteractHold;
                @MainInteractHold.performed -= instance.OnMainInteractHold;
                @MainInteractHold.canceled -= instance.OnMainInteractHold;
                @SubInteract.started -= instance.OnSubInteract;
                @SubInteract.performed -= instance.OnSubInteract;
                @SubInteract.canceled -= instance.OnSubInteract;
                @SubInteractHold.started -= instance.OnSubInteractHold;
                @SubInteractHold.performed -= instance.OnSubInteractHold;
                @SubInteractHold.canceled -= instance.OnSubInteractHold;
            }

            public void RemoveCallbacks(ICommonActions instance)
            {
                if (m_Wrapper.m_CommonActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(ICommonActions instance)
            {
                foreach (var item in m_Wrapper.m_CommonActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_CommonActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public CommonActions @Common => new CommonActions(this);

        // StartMenu
        private readonly InputActionMap m_StartMenu;
        private List<IStartMenuActions> m_StartMenuActionsCallbackInterfaces = new List<IStartMenuActions>();
        private readonly InputAction m_StartMenu_SwichBtn;
        public struct StartMenuActions
        {
            private @CommomInput m_Wrapper;
            public StartMenuActions(@CommomInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @SwichBtn => m_Wrapper.m_StartMenu_SwichBtn;
            public InputActionMap Get() { return m_Wrapper.m_StartMenu; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(StartMenuActions set) { return set.Get(); }
            public void AddCallbacks(IStartMenuActions instance)
            {
                if (instance == null || m_Wrapper.m_StartMenuActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_StartMenuActionsCallbackInterfaces.Add(instance);
                @SwichBtn.started += instance.OnSwichBtn;
                @SwichBtn.performed += instance.OnSwichBtn;
                @SwichBtn.canceled += instance.OnSwichBtn;
            }

            private void UnregisterCallbacks(IStartMenuActions instance)
            {
                @SwichBtn.started -= instance.OnSwichBtn;
                @SwichBtn.performed -= instance.OnSwichBtn;
                @SwichBtn.canceled -= instance.OnSwichBtn;
            }

            public void RemoveCallbacks(IStartMenuActions instance)
            {
                if (m_Wrapper.m_StartMenuActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IStartMenuActions instance)
            {
                foreach (var item in m_Wrapper.m_StartMenuActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_StartMenuActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public StartMenuActions @StartMenu => new StartMenuActions(this);

        // Option
        private readonly InputActionMap m_Option;
        private List<IOptionActions> m_OptionActionsCallbackInterfaces = new List<IOptionActions>();
        private readonly InputAction m_Option_SwichBtn;
        public struct OptionActions
        {
            private @CommomInput m_Wrapper;
            public OptionActions(@CommomInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @SwichBtn => m_Wrapper.m_Option_SwichBtn;
            public InputActionMap Get() { return m_Wrapper.m_Option; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(OptionActions set) { return set.Get(); }
            public void AddCallbacks(IOptionActions instance)
            {
                if (instance == null || m_Wrapper.m_OptionActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_OptionActionsCallbackInterfaces.Add(instance);
                @SwichBtn.started += instance.OnSwichBtn;
                @SwichBtn.performed += instance.OnSwichBtn;
                @SwichBtn.canceled += instance.OnSwichBtn;
            }

            private void UnregisterCallbacks(IOptionActions instance)
            {
                @SwichBtn.started -= instance.OnSwichBtn;
                @SwichBtn.performed -= instance.OnSwichBtn;
                @SwichBtn.canceled -= instance.OnSwichBtn;
            }

            public void RemoveCallbacks(IOptionActions instance)
            {
                if (m_Wrapper.m_OptionActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IOptionActions instance)
            {
                foreach (var item in m_Wrapper.m_OptionActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_OptionActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public OptionActions @Option => new OptionActions(this);
        public interface ICommonActions
        {
            void OnConfirm(InputAction.CallbackContext context);
            void OnRT(InputAction.CallbackContext context);
            void OnConfirmHold(InputAction.CallbackContext context);
            void OnSwichBtn(InputAction.CallbackContext context);
            void OnTurnPage(InputAction.CallbackContext context);
            void OnBack(InputAction.CallbackContext context);
            void OnNextTerm(InputAction.CallbackContext context);
            void OnLastTerm(InputAction.CallbackContext context);
            void OnMainInteract(InputAction.CallbackContext context);
            void OnMainInteractHold(InputAction.CallbackContext context);
            void OnSubInteract(InputAction.CallbackContext context);
            void OnSubInteractHold(InputAction.CallbackContext context);
        }
        public interface IStartMenuActions
        {
            void OnSwichBtn(InputAction.CallbackContext context);
        }
        public interface IOptionActions
        {
            void OnSwichBtn(InputAction.CallbackContext context);
        }
    }
}
