//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/_ML/Engine/BuildingSystem/BuildingInput/BuildingInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace ML.Engine.BuildingSystem.Input
{
    public partial class @BuildingInput: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @BuildingInput()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""BuildingInput"",
    ""maps"": [
        {
            ""name"": ""Build"",
            ""id"": ""1a60932b-59da-4272-9e64-a8722998c871"",
            ""actions"": [
                {
                    ""name"": ""MoveBuild"",
                    ""type"": ""Button"",
                    ""id"": ""a4df4b1b-e5ae-4b72-a2f8-b876e7f13040"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DestroyBuild"",
                    ""type"": ""Button"",
                    ""id"": ""2bdb8b6c-4d96-467c-8c4d-1512805d04b8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeOutLook"",
                    ""type"": ""Button"",
                    ""id"": ""d6753e72-4391-49b7-a0f1-a8bacfd65c65"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeInteractiveActor"",
                    ""type"": ""Value"",
                    ""id"": ""ed422134-a3ab-4367-9005-75feabed63f1"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SelectBuild"",
                    ""type"": ""Button"",
                    ""id"": ""b850f8ab-6c51-4881-a845-328fd3db79de"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""KeyCom"",
                    ""type"": ""Button"",
                    ""id"": ""6ebb1015-d2b0-4cc6-8c83-bb2ace996c94"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=0.1,pressPoint=0.5)"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""321a799b-a9c2-4402-a62a-84e5e99bb614"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveBuild"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4866bda-2653-4d3c-87fa-e9f8b2385373"",
                    ""path"": ""<XInputController>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveBuild"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2fa582fc-d1f1-458e-ac4b-5be61fcef9a5"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DestroyBuild"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ef82ddf2-1533-47d0-9a3b-29f1f5927e1d"",
                    ""path"": ""<XInputController>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DestroyBuild"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1b4c512-f0be-4697-96eb-c1e0c39f8884"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeOutLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7bd59699-73ac-400b-b8de-ca05ed2599d5"",
                    ""path"": ""<XInputController>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeOutLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a63d8cb5-3b7f-4cde-ba49-b9ef06f62730"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectBuild"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""082aa5a5-abe2-4313-992a-687004755fbf"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectBuild"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""df188c4e-a150-444d-814f-6990ece9bd3a"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyCom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0236c76e-c0bd-4895-91ef-417cf4ce9d4e"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyCom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""450a1c5e-e785-4974-830f-45ef1e638873"",
                    ""path"": ""<XInputController>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyCom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""MouseScroll"",
                    ""id"": ""61e9a711-45a8-4e22-aec8-b1ba26c6684f"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeInteractiveActor"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""84609156-2326-45d7-baea-68f6bde64c96"",
                    ""path"": ""<Mouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeInteractiveActor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""1cdbcdc5-6b81-4a8e-98be-88aa921e1e99"",
                    ""path"": ""<Mouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeInteractiveActor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""XBOX"",
                    ""id"": ""76a0b217-2911-4e99-8ea0-fd7f7b2449fd"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeInteractiveActor"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""d851fabf-cd1b-4a1c-8443-eff87873ba7b"",
                    ""path"": ""<XInputController>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeInteractiveActor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""84dca2d7-2b0e-468c-a1f4-fe29b7e04d54"",
                    ""path"": ""<XInputController>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeInteractiveActor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""XBOX"",
                    ""id"": ""9f71e855-284c-4219-a3c7-794d08d7915f"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeInteractiveActor"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""92c1ba92-8c84-47f8-b222-c49dcc770fc9"",
                    ""path"": ""<XInputController>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeInteractiveActor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""08b1cdc2-7232-4d54-9399-ff6d577d5ab9"",
                    ""path"": ""<XInputController>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeInteractiveActor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""BuildKeyCom"",
            ""id"": ""65124ae5-e03b-455f-ac3e-c9a74490146c"",
            ""actions"": [
                {
                    ""name"": ""KeyCom"",
                    ""type"": ""Button"",
                    ""id"": ""52df4198-e4ea-45a5-b8e9-01e41c63feba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CopyBuild"",
                    ""type"": ""Button"",
                    ""id"": ""2f9bbb84-f0b9-434f-94c5-40cf244ddbf1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PasteOutLook"",
                    ""type"": ""Button"",
                    ""id"": ""9b8969d7-0582-4fe2-a0fd-bf2ba29e0190"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CopyOutLook"",
                    ""type"": ""Button"",
                    ""id"": ""c65a350d-dc82-42fe-abab-2511d2566086"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""cdaa8ffa-0334-46b7-9f42-7b73deefc914"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyCom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""febf9598-bf74-4b61-a0b2-ba18bae1d6df"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyCom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c45167eb-25b4-4688-962b-5838c5c05925"",
                    ""path"": ""<XInputController>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyCom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""842c8f97-2192-4759-91ee-854c16bd9b9e"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CopyBuild"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""73dcb7cc-66e2-42c5-a1dd-6ef26d4cf7e9"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CopyBuild"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8ba89a9a-f145-4aab-aa9e-592c3b764219"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PasteOutLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3127b9b9-2646-4b5a-93fc-858c51598857"",
                    ""path"": ""<XInputController>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PasteOutLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7d215dae-3867-49ae-bbc4-afd7f08715f3"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CopyOutLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""251ce0e1-4094-42fb-9d9f-e72d616fc104"",
                    ""path"": ""<XInputController>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CopyOutLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""BuildSelection"",
            ""id"": ""86e742eb-f156-4860-bd12-95a9e81c2e4b"",
            ""actions"": [
                {
                    ""name"": ""AlternativeType"",
                    ""type"": ""Value"",
                    ""id"": ""67ae47b2-4c19-417b-93c9-707ae97533ad"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""AlterCategory"",
                    ""type"": ""Value"",
                    ""id"": ""9ae20fe6-35b4-4fb5-a192-9b08c4d8ca95"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ChangeFurnitureDisplay"",
                    ""type"": ""Button"",
                    ""id"": ""2a6bc70c-f1c5-4edc-a1d5-e1de4276a6ae"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwichBtn"",
                    ""type"": ""Value"",
                    ""id"": ""89b0c7a5-5248-4377-9380-8e9e42fce4ca"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""483e0ab8-30fc-4e49-b75a-08665e70ae94"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AlternativeType"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""73caa78c-988b-4806-bb81-4e62d6f32b43"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AlternativeType"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""9c916b08-dbb9-4870-838a-e79112cd989c"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AlternativeType"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""XBOX"",
                    ""id"": ""8ffd3e8b-188f-43f8-8e10-a7d6c7b6cde1"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AlternativeType"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""a3cc6455-741e-4b65-8b06-b255da69c815"",
                    ""path"": ""<XInputController>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AlternativeType"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""cf6182e9-e02b-4c1e-ae83-95d98d75fb07"",
                    ""path"": ""<XInputController>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AlternativeType"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""317f5eb9-b917-410a-bf5b-a032cba51be9"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AlterCategory"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""d0360d64-dd8c-4fe4-8da9-698ad6c1fbeb"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AlterCategory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""287ce11f-1364-46eb-8997-e36a4ec69a8e"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AlterCategory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""XBOX"",
                    ""id"": ""0ecc47bd-618c-47c0-af98-66cb35ba617d"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AlterCategory"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""5578801c-95ba-4f8e-ae51-ee6bdff8c9bd"",
                    ""path"": ""<XInputController>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AlterCategory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""456c1169-c1ad-40e2-ac16-e29ef9ceb748"",
                    ""path"": ""<XInputController>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AlterCategory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c02710b0-c2f1-400b-a853-b2506f4d75f1"",
                    ""path"": ""<XInputController>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeFurnitureDisplay"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1922873-5dbc-4e47-8d56-8476b3a58ac7"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeFurnitureDisplay"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""KeyBoard"",
                    ""id"": ""4791472b-c80c-4ca4-9519-b8440a26bb0d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c8e882c2-ec80-49ee-8726-49403fc4adac"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""67bad660-62e1-4479-9a2d-4baac1b41ce4"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""02745c08-c255-4fb3-84c2-40267e2ffd26"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""cce6280b-7543-4896-924e-be9e06394f55"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""XBOX"",
                    ""id"": ""7350bd6f-2c16-4584-b6f2-1f31dfdb4602"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""819c2542-10fb-46d1-ace7-0c6023c4ffd8"",
                    ""path"": ""<XInputController>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7ddd5fc7-8db8-4119-b232-c418ede44828"",
                    ""path"": ""<XInputController>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""5712e882-4d0d-48c4-8466-791bc3a87aae"",
                    ""path"": ""<XInputController>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""0c5d8ee6-5a34-4223-8cc6-330f1d673b8b"",
                    ""path"": ""<XInputController>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwichBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""BuildingAppearance"",
            ""id"": ""611aa345-2247-4628-bd0b-c3a5fa713d1e"",
            ""actions"": [
                {
                    ""name"": ""AlterMaterial"",
                    ""type"": ""Value"",
                    ""id"": ""8e394451-e02f-4eb4-b6b2-19591c1882e7"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""68c99d8d-0248-4c66-b281-ca943a3166a1"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AlterMaterial"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""down"",
                    ""id"": ""108ce15b-beb0-4cfe-91b3-a17c31652f52"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AlterMaterial"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""31d71030-5c99-4bef-a9be-7432b2671763"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AlterMaterial"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""2c24fa18-66d9-4f3d-ab6b-ef3946b7640c"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AlterMaterial"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e95a14be-62d7-4c7a-bbbc-666784fa6090"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AlterMaterial"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""XBOX"",
                    ""id"": ""daf0ecd7-70aa-4831-a13b-b96e121e4c06"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AlterMaterial"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ef12212a-7905-41fc-aafc-d2487349ac34"",
                    ""path"": ""<XInputController>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AlterMaterial"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""c9d4dcb5-1b83-44a0-b4f7-541a6b5e9c9d"",
                    ""path"": ""<XInputController>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AlterMaterial"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""374fc5e4-0036-428b-9acf-24720ef58367"",
                    ""path"": ""<XInputController>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AlterMaterial"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""2dd7100d-b49b-4269-93a6-4f7a499f40ff"",
                    ""path"": ""<XInputController>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AlterMaterial"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""BuildPlaceMode"",
            ""id"": ""aa6189dd-7e52-4e07-9f89-fcb21cae037d"",
            ""actions"": [
                {
                    ""name"": ""ChangeActiveSocket"",
                    ""type"": ""Button"",
                    ""id"": ""94006188-f966-4a8a-b49e-26cc9ac38764"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeOutLook"",
                    ""type"": ""Button"",
                    ""id"": ""e5338be8-e112-400b-af6d-a5497c2fadfe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchFrame_PreHold"",
                    ""type"": ""Button"",
                    ""id"": ""5d5c7fa2-49f4-4da3-a2bb-60f181dc8fcc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchFrame_PostPress"",
                    ""type"": ""Button"",
                    ""id"": ""d3e56b1c-91c9-4835-8a80-8b15cbac7f89"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""KeyCom"",
                    ""type"": ""Button"",
                    ""id"": ""d7842ae6-4dc9-4acc-92f7-1eb82b90848a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Value"",
                    ""id"": ""65e49564-5e6a-4c1f-8389-0250ad83431c"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ChangeHeight"",
                    ""type"": ""Value"",
                    ""id"": ""55f3e379-f28e-4ffa-bf5b-71aed9bec33f"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ChangeStyle"",
                    ""type"": ""Value"",
                    ""id"": ""ad1ffcee-6ec1-4ab7-8133-c09eea93d35c"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7aaab952-0ed2-48fb-a3db-be9cb5b594e9"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeActiveSocket"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""455a1c5f-082a-4d43-acfb-f88fb9a96fba"",
                    ""path"": ""<XInputController>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeActiveSocket"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f17db4ce-97f1-47a5-95c1-928137ef0d78"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeOutLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b3402f97-e1d4-48f9-a5e5-1f36b04abb14"",
                    ""path"": ""<XInputController>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeOutLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c05bb18a-3a3d-404b-9bfb-f80d22522a4e"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchFrame_PreHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d09e2b38-a6d4-4d61-83e8-250bab400312"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchFrame_PreHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""47de7bb2-3072-4459-a43c-f5dcdf88b6f5"",
                    ""path"": ""<XInputController>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchFrame_PreHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b7370621-8a8d-4258-9736-8fc49ef15b59"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchFrame_PostPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41273eb5-fcd6-4288-ae67-31f75cd859f8"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchFrame_PostPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a1b943a2-f3f6-4ee5-aaea-850f546ff61c"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyCom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0570d0a5-f9b9-4c21-b412-1dcd827ed9cc"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyCom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""69f15ada-1a42-4eff-975a-295fefcd46b9"",
                    ""path"": ""<XInputController>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyCom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""1e9b1061-d28f-4cc7-be9a-0a0a565e4b84"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""5768cd4a-1a14-42f6-8929-4d508cc659f1"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""81057847-24f7-4a92-8b22-289517189228"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""XBOX"",
                    ""id"": ""5c324f79-97b8-43d4-aa78-6e1f1a88b612"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""c5be6e3b-7a62-4671-8e22-d8e55ff37bb0"",
                    ""path"": ""<XInputController>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""db5cc0f1-b403-4cde-aaf6-571f37e31d9a"",
                    ""path"": ""<XInputController>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""1a9dc6aa-52c1-4c5f-9ee1-299c5c335ab2"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeHeight"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""50e9a65b-8685-4a34-82c1-1919fa513122"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeHeight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""cf43c287-a25c-44c3-b80f-15046a6e0160"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeHeight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""XBOX"",
                    ""id"": ""ed341dac-7e29-493b-8217-75e73bd6ab89"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeHeight"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""59c765ff-bd42-4e3d-b86f-bf456f666513"",
                    ""path"": ""<XInputController>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeHeight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""350e4a3a-e6c8-423e-a32b-80fde4c64c89"",
                    ""path"": ""<XInputController>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeHeight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""9c9c7df7-27ec-462c-be55-5c371b4fcf07"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeStyle"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""9843507c-ca24-4a92-af0b-89dbd48e04b2"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeStyle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""6a031366-6d2d-4128-9122-b3005ca64a4d"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeStyle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""XBOX"",
                    ""id"": ""4816162b-6f85-4046-b18d-8a19bdc0e876"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeStyle"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""5a84f459-823e-4238-b26b-3b6cdf2f8002"",
                    ""path"": ""<XInputController>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeStyle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""60b0a9c4-8d51-4d31-8ced-8e0c78fdac6d"",
                    ""path"": ""<XInputController>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeStyle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Build
            m_Build = asset.FindActionMap("Build", throwIfNotFound: true);
            m_Build_MoveBuild = m_Build.FindAction("MoveBuild", throwIfNotFound: true);
            m_Build_DestroyBuild = m_Build.FindAction("DestroyBuild", throwIfNotFound: true);
            m_Build_ChangeOutLook = m_Build.FindAction("ChangeOutLook", throwIfNotFound: true);
            m_Build_ChangeInteractiveActor = m_Build.FindAction("ChangeInteractiveActor", throwIfNotFound: true);
            m_Build_SelectBuild = m_Build.FindAction("SelectBuild", throwIfNotFound: true);
            m_Build_KeyCom = m_Build.FindAction("KeyCom", throwIfNotFound: true);
            // BuildKeyCom
            m_BuildKeyCom = asset.FindActionMap("BuildKeyCom", throwIfNotFound: true);
            m_BuildKeyCom_KeyCom = m_BuildKeyCom.FindAction("KeyCom", throwIfNotFound: true);
            m_BuildKeyCom_CopyBuild = m_BuildKeyCom.FindAction("CopyBuild", throwIfNotFound: true);
            m_BuildKeyCom_PasteOutLook = m_BuildKeyCom.FindAction("PasteOutLook", throwIfNotFound: true);
            m_BuildKeyCom_CopyOutLook = m_BuildKeyCom.FindAction("CopyOutLook", throwIfNotFound: true);
            // BuildSelection
            m_BuildSelection = asset.FindActionMap("BuildSelection", throwIfNotFound: true);
            m_BuildSelection_AlternativeType = m_BuildSelection.FindAction("AlternativeType", throwIfNotFound: true);
            m_BuildSelection_AlterCategory = m_BuildSelection.FindAction("AlterCategory", throwIfNotFound: true);
            m_BuildSelection_ChangeFurnitureDisplay = m_BuildSelection.FindAction("ChangeFurnitureDisplay", throwIfNotFound: true);
            m_BuildSelection_SwichBtn = m_BuildSelection.FindAction("SwichBtn", throwIfNotFound: true);
            // BuildingAppearance
            m_BuildingAppearance = asset.FindActionMap("BuildingAppearance", throwIfNotFound: true);
            m_BuildingAppearance_AlterMaterial = m_BuildingAppearance.FindAction("AlterMaterial", throwIfNotFound: true);
            // BuildPlaceMode
            m_BuildPlaceMode = asset.FindActionMap("BuildPlaceMode", throwIfNotFound: true);
            m_BuildPlaceMode_ChangeActiveSocket = m_BuildPlaceMode.FindAction("ChangeActiveSocket", throwIfNotFound: true);
            m_BuildPlaceMode_ChangeOutLook = m_BuildPlaceMode.FindAction("ChangeOutLook", throwIfNotFound: true);
            m_BuildPlaceMode_SwitchFrame_PreHold = m_BuildPlaceMode.FindAction("SwitchFrame_PreHold", throwIfNotFound: true);
            m_BuildPlaceMode_SwitchFrame_PostPress = m_BuildPlaceMode.FindAction("SwitchFrame_PostPress", throwIfNotFound: true);
            m_BuildPlaceMode_KeyCom = m_BuildPlaceMode.FindAction("KeyCom", throwIfNotFound: true);
            m_BuildPlaceMode_Rotate = m_BuildPlaceMode.FindAction("Rotate", throwIfNotFound: true);
            m_BuildPlaceMode_ChangeHeight = m_BuildPlaceMode.FindAction("ChangeHeight", throwIfNotFound: true);
            m_BuildPlaceMode_ChangeStyle = m_BuildPlaceMode.FindAction("ChangeStyle", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Build
        private readonly InputActionMap m_Build;
        private List<IBuildActions> m_BuildActionsCallbackInterfaces = new List<IBuildActions>();
        private readonly InputAction m_Build_MoveBuild;
        private readonly InputAction m_Build_DestroyBuild;
        private readonly InputAction m_Build_ChangeOutLook;
        private readonly InputAction m_Build_ChangeInteractiveActor;
        private readonly InputAction m_Build_SelectBuild;
        private readonly InputAction m_Build_KeyCom;
        public struct BuildActions
        {
            private @BuildingInput m_Wrapper;
            public BuildActions(@BuildingInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @MoveBuild => m_Wrapper.m_Build_MoveBuild;
            public InputAction @DestroyBuild => m_Wrapper.m_Build_DestroyBuild;
            public InputAction @ChangeOutLook => m_Wrapper.m_Build_ChangeOutLook;
            public InputAction @ChangeInteractiveActor => m_Wrapper.m_Build_ChangeInteractiveActor;
            public InputAction @SelectBuild => m_Wrapper.m_Build_SelectBuild;
            public InputAction @KeyCom => m_Wrapper.m_Build_KeyCom;
            public InputActionMap Get() { return m_Wrapper.m_Build; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(BuildActions set) { return set.Get(); }
            public void AddCallbacks(IBuildActions instance)
            {
                if (instance == null || m_Wrapper.m_BuildActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_BuildActionsCallbackInterfaces.Add(instance);
                @MoveBuild.started += instance.OnMoveBuild;
                @MoveBuild.performed += instance.OnMoveBuild;
                @MoveBuild.canceled += instance.OnMoveBuild;
                @DestroyBuild.started += instance.OnDestroyBuild;
                @DestroyBuild.performed += instance.OnDestroyBuild;
                @DestroyBuild.canceled += instance.OnDestroyBuild;
                @ChangeOutLook.started += instance.OnChangeOutLook;
                @ChangeOutLook.performed += instance.OnChangeOutLook;
                @ChangeOutLook.canceled += instance.OnChangeOutLook;
                @ChangeInteractiveActor.started += instance.OnChangeInteractiveActor;
                @ChangeInteractiveActor.performed += instance.OnChangeInteractiveActor;
                @ChangeInteractiveActor.canceled += instance.OnChangeInteractiveActor;
                @SelectBuild.started += instance.OnSelectBuild;
                @SelectBuild.performed += instance.OnSelectBuild;
                @SelectBuild.canceled += instance.OnSelectBuild;
                @KeyCom.started += instance.OnKeyCom;
                @KeyCom.performed += instance.OnKeyCom;
                @KeyCom.canceled += instance.OnKeyCom;
            }

            private void UnregisterCallbacks(IBuildActions instance)
            {
                @MoveBuild.started -= instance.OnMoveBuild;
                @MoveBuild.performed -= instance.OnMoveBuild;
                @MoveBuild.canceled -= instance.OnMoveBuild;
                @DestroyBuild.started -= instance.OnDestroyBuild;
                @DestroyBuild.performed -= instance.OnDestroyBuild;
                @DestroyBuild.canceled -= instance.OnDestroyBuild;
                @ChangeOutLook.started -= instance.OnChangeOutLook;
                @ChangeOutLook.performed -= instance.OnChangeOutLook;
                @ChangeOutLook.canceled -= instance.OnChangeOutLook;
                @ChangeInteractiveActor.started -= instance.OnChangeInteractiveActor;
                @ChangeInteractiveActor.performed -= instance.OnChangeInteractiveActor;
                @ChangeInteractiveActor.canceled -= instance.OnChangeInteractiveActor;
                @SelectBuild.started -= instance.OnSelectBuild;
                @SelectBuild.performed -= instance.OnSelectBuild;
                @SelectBuild.canceled -= instance.OnSelectBuild;
                @KeyCom.started -= instance.OnKeyCom;
                @KeyCom.performed -= instance.OnKeyCom;
                @KeyCom.canceled -= instance.OnKeyCom;
            }

            public void RemoveCallbacks(IBuildActions instance)
            {
                if (m_Wrapper.m_BuildActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IBuildActions instance)
            {
                foreach (var item in m_Wrapper.m_BuildActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_BuildActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public BuildActions @Build => new BuildActions(this);

        // BuildKeyCom
        private readonly InputActionMap m_BuildKeyCom;
        private List<IBuildKeyComActions> m_BuildKeyComActionsCallbackInterfaces = new List<IBuildKeyComActions>();
        private readonly InputAction m_BuildKeyCom_KeyCom;
        private readonly InputAction m_BuildKeyCom_CopyBuild;
        private readonly InputAction m_BuildKeyCom_PasteOutLook;
        private readonly InputAction m_BuildKeyCom_CopyOutLook;
        public struct BuildKeyComActions
        {
            private @BuildingInput m_Wrapper;
            public BuildKeyComActions(@BuildingInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @KeyCom => m_Wrapper.m_BuildKeyCom_KeyCom;
            public InputAction @CopyBuild => m_Wrapper.m_BuildKeyCom_CopyBuild;
            public InputAction @PasteOutLook => m_Wrapper.m_BuildKeyCom_PasteOutLook;
            public InputAction @CopyOutLook => m_Wrapper.m_BuildKeyCom_CopyOutLook;
            public InputActionMap Get() { return m_Wrapper.m_BuildKeyCom; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(BuildKeyComActions set) { return set.Get(); }
            public void AddCallbacks(IBuildKeyComActions instance)
            {
                if (instance == null || m_Wrapper.m_BuildKeyComActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_BuildKeyComActionsCallbackInterfaces.Add(instance);
                @KeyCom.started += instance.OnKeyCom;
                @KeyCom.performed += instance.OnKeyCom;
                @KeyCom.canceled += instance.OnKeyCom;
                @CopyBuild.started += instance.OnCopyBuild;
                @CopyBuild.performed += instance.OnCopyBuild;
                @CopyBuild.canceled += instance.OnCopyBuild;
                @PasteOutLook.started += instance.OnPasteOutLook;
                @PasteOutLook.performed += instance.OnPasteOutLook;
                @PasteOutLook.canceled += instance.OnPasteOutLook;
                @CopyOutLook.started += instance.OnCopyOutLook;
                @CopyOutLook.performed += instance.OnCopyOutLook;
                @CopyOutLook.canceled += instance.OnCopyOutLook;
            }

            private void UnregisterCallbacks(IBuildKeyComActions instance)
            {
                @KeyCom.started -= instance.OnKeyCom;
                @KeyCom.performed -= instance.OnKeyCom;
                @KeyCom.canceled -= instance.OnKeyCom;
                @CopyBuild.started -= instance.OnCopyBuild;
                @CopyBuild.performed -= instance.OnCopyBuild;
                @CopyBuild.canceled -= instance.OnCopyBuild;
                @PasteOutLook.started -= instance.OnPasteOutLook;
                @PasteOutLook.performed -= instance.OnPasteOutLook;
                @PasteOutLook.canceled -= instance.OnPasteOutLook;
                @CopyOutLook.started -= instance.OnCopyOutLook;
                @CopyOutLook.performed -= instance.OnCopyOutLook;
                @CopyOutLook.canceled -= instance.OnCopyOutLook;
            }

            public void RemoveCallbacks(IBuildKeyComActions instance)
            {
                if (m_Wrapper.m_BuildKeyComActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IBuildKeyComActions instance)
            {
                foreach (var item in m_Wrapper.m_BuildKeyComActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_BuildKeyComActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public BuildKeyComActions @BuildKeyCom => new BuildKeyComActions(this);

        // BuildSelection
        private readonly InputActionMap m_BuildSelection;
        private List<IBuildSelectionActions> m_BuildSelectionActionsCallbackInterfaces = new List<IBuildSelectionActions>();
        private readonly InputAction m_BuildSelection_AlternativeType;
        private readonly InputAction m_BuildSelection_AlterCategory;
        private readonly InputAction m_BuildSelection_ChangeFurnitureDisplay;
        private readonly InputAction m_BuildSelection_SwichBtn;
        public struct BuildSelectionActions
        {
            private @BuildingInput m_Wrapper;
            public BuildSelectionActions(@BuildingInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @AlternativeType => m_Wrapper.m_BuildSelection_AlternativeType;
            public InputAction @AlterCategory => m_Wrapper.m_BuildSelection_AlterCategory;
            public InputAction @ChangeFurnitureDisplay => m_Wrapper.m_BuildSelection_ChangeFurnitureDisplay;
            public InputAction @SwichBtn => m_Wrapper.m_BuildSelection_SwichBtn;
            public InputActionMap Get() { return m_Wrapper.m_BuildSelection; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(BuildSelectionActions set) { return set.Get(); }
            public void AddCallbacks(IBuildSelectionActions instance)
            {
                if (instance == null || m_Wrapper.m_BuildSelectionActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_BuildSelectionActionsCallbackInterfaces.Add(instance);
                @AlternativeType.started += instance.OnAlternativeType;
                @AlternativeType.performed += instance.OnAlternativeType;
                @AlternativeType.canceled += instance.OnAlternativeType;
                @AlterCategory.started += instance.OnAlterCategory;
                @AlterCategory.performed += instance.OnAlterCategory;
                @AlterCategory.canceled += instance.OnAlterCategory;
                @ChangeFurnitureDisplay.started += instance.OnChangeFurnitureDisplay;
                @ChangeFurnitureDisplay.performed += instance.OnChangeFurnitureDisplay;
                @ChangeFurnitureDisplay.canceled += instance.OnChangeFurnitureDisplay;
                @SwichBtn.started += instance.OnSwichBtn;
                @SwichBtn.performed += instance.OnSwichBtn;
                @SwichBtn.canceled += instance.OnSwichBtn;
            }

            private void UnregisterCallbacks(IBuildSelectionActions instance)
            {
                @AlternativeType.started -= instance.OnAlternativeType;
                @AlternativeType.performed -= instance.OnAlternativeType;
                @AlternativeType.canceled -= instance.OnAlternativeType;
                @AlterCategory.started -= instance.OnAlterCategory;
                @AlterCategory.performed -= instance.OnAlterCategory;
                @AlterCategory.canceled -= instance.OnAlterCategory;
                @ChangeFurnitureDisplay.started -= instance.OnChangeFurnitureDisplay;
                @ChangeFurnitureDisplay.performed -= instance.OnChangeFurnitureDisplay;
                @ChangeFurnitureDisplay.canceled -= instance.OnChangeFurnitureDisplay;
                @SwichBtn.started -= instance.OnSwichBtn;
                @SwichBtn.performed -= instance.OnSwichBtn;
                @SwichBtn.canceled -= instance.OnSwichBtn;
            }

            public void RemoveCallbacks(IBuildSelectionActions instance)
            {
                if (m_Wrapper.m_BuildSelectionActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IBuildSelectionActions instance)
            {
                foreach (var item in m_Wrapper.m_BuildSelectionActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_BuildSelectionActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public BuildSelectionActions @BuildSelection => new BuildSelectionActions(this);

        // BuildingAppearance
        private readonly InputActionMap m_BuildingAppearance;
        private List<IBuildingAppearanceActions> m_BuildingAppearanceActionsCallbackInterfaces = new List<IBuildingAppearanceActions>();
        private readonly InputAction m_BuildingAppearance_AlterMaterial;
        public struct BuildingAppearanceActions
        {
            private @BuildingInput m_Wrapper;
            public BuildingAppearanceActions(@BuildingInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @AlterMaterial => m_Wrapper.m_BuildingAppearance_AlterMaterial;
            public InputActionMap Get() { return m_Wrapper.m_BuildingAppearance; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(BuildingAppearanceActions set) { return set.Get(); }
            public void AddCallbacks(IBuildingAppearanceActions instance)
            {
                if (instance == null || m_Wrapper.m_BuildingAppearanceActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_BuildingAppearanceActionsCallbackInterfaces.Add(instance);
                @AlterMaterial.started += instance.OnAlterMaterial;
                @AlterMaterial.performed += instance.OnAlterMaterial;
                @AlterMaterial.canceled += instance.OnAlterMaterial;
            }

            private void UnregisterCallbacks(IBuildingAppearanceActions instance)
            {
                @AlterMaterial.started -= instance.OnAlterMaterial;
                @AlterMaterial.performed -= instance.OnAlterMaterial;
                @AlterMaterial.canceled -= instance.OnAlterMaterial;
            }

            public void RemoveCallbacks(IBuildingAppearanceActions instance)
            {
                if (m_Wrapper.m_BuildingAppearanceActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IBuildingAppearanceActions instance)
            {
                foreach (var item in m_Wrapper.m_BuildingAppearanceActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_BuildingAppearanceActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public BuildingAppearanceActions @BuildingAppearance => new BuildingAppearanceActions(this);

        // BuildPlaceMode
        private readonly InputActionMap m_BuildPlaceMode;
        private List<IBuildPlaceModeActions> m_BuildPlaceModeActionsCallbackInterfaces = new List<IBuildPlaceModeActions>();
        private readonly InputAction m_BuildPlaceMode_ChangeActiveSocket;
        private readonly InputAction m_BuildPlaceMode_ChangeOutLook;
        private readonly InputAction m_BuildPlaceMode_SwitchFrame_PreHold;
        private readonly InputAction m_BuildPlaceMode_SwitchFrame_PostPress;
        private readonly InputAction m_BuildPlaceMode_KeyCom;
        private readonly InputAction m_BuildPlaceMode_Rotate;
        private readonly InputAction m_BuildPlaceMode_ChangeHeight;
        private readonly InputAction m_BuildPlaceMode_ChangeStyle;
        public struct BuildPlaceModeActions
        {
            private @BuildingInput m_Wrapper;
            public BuildPlaceModeActions(@BuildingInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @ChangeActiveSocket => m_Wrapper.m_BuildPlaceMode_ChangeActiveSocket;
            public InputAction @ChangeOutLook => m_Wrapper.m_BuildPlaceMode_ChangeOutLook;
            public InputAction @SwitchFrame_PreHold => m_Wrapper.m_BuildPlaceMode_SwitchFrame_PreHold;
            public InputAction @SwitchFrame_PostPress => m_Wrapper.m_BuildPlaceMode_SwitchFrame_PostPress;
            public InputAction @KeyCom => m_Wrapper.m_BuildPlaceMode_KeyCom;
            public InputAction @Rotate => m_Wrapper.m_BuildPlaceMode_Rotate;
            public InputAction @ChangeHeight => m_Wrapper.m_BuildPlaceMode_ChangeHeight;
            public InputAction @ChangeStyle => m_Wrapper.m_BuildPlaceMode_ChangeStyle;
            public InputActionMap Get() { return m_Wrapper.m_BuildPlaceMode; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(BuildPlaceModeActions set) { return set.Get(); }
            public void AddCallbacks(IBuildPlaceModeActions instance)
            {
                if (instance == null || m_Wrapper.m_BuildPlaceModeActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_BuildPlaceModeActionsCallbackInterfaces.Add(instance);
                @ChangeActiveSocket.started += instance.OnChangeActiveSocket;
                @ChangeActiveSocket.performed += instance.OnChangeActiveSocket;
                @ChangeActiveSocket.canceled += instance.OnChangeActiveSocket;
                @ChangeOutLook.started += instance.OnChangeOutLook;
                @ChangeOutLook.performed += instance.OnChangeOutLook;
                @ChangeOutLook.canceled += instance.OnChangeOutLook;
                @SwitchFrame_PreHold.started += instance.OnSwitchFrame_PreHold;
                @SwitchFrame_PreHold.performed += instance.OnSwitchFrame_PreHold;
                @SwitchFrame_PreHold.canceled += instance.OnSwitchFrame_PreHold;
                @SwitchFrame_PostPress.started += instance.OnSwitchFrame_PostPress;
                @SwitchFrame_PostPress.performed += instance.OnSwitchFrame_PostPress;
                @SwitchFrame_PostPress.canceled += instance.OnSwitchFrame_PostPress;
                @KeyCom.started += instance.OnKeyCom;
                @KeyCom.performed += instance.OnKeyCom;
                @KeyCom.canceled += instance.OnKeyCom;
                @Rotate.started += instance.OnRotate;
                @Rotate.performed += instance.OnRotate;
                @Rotate.canceled += instance.OnRotate;
                @ChangeHeight.started += instance.OnChangeHeight;
                @ChangeHeight.performed += instance.OnChangeHeight;
                @ChangeHeight.canceled += instance.OnChangeHeight;
                @ChangeStyle.started += instance.OnChangeStyle;
                @ChangeStyle.performed += instance.OnChangeStyle;
                @ChangeStyle.canceled += instance.OnChangeStyle;
            }

            private void UnregisterCallbacks(IBuildPlaceModeActions instance)
            {
                @ChangeActiveSocket.started -= instance.OnChangeActiveSocket;
                @ChangeActiveSocket.performed -= instance.OnChangeActiveSocket;
                @ChangeActiveSocket.canceled -= instance.OnChangeActiveSocket;
                @ChangeOutLook.started -= instance.OnChangeOutLook;
                @ChangeOutLook.performed -= instance.OnChangeOutLook;
                @ChangeOutLook.canceled -= instance.OnChangeOutLook;
                @SwitchFrame_PreHold.started -= instance.OnSwitchFrame_PreHold;
                @SwitchFrame_PreHold.performed -= instance.OnSwitchFrame_PreHold;
                @SwitchFrame_PreHold.canceled -= instance.OnSwitchFrame_PreHold;
                @SwitchFrame_PostPress.started -= instance.OnSwitchFrame_PostPress;
                @SwitchFrame_PostPress.performed -= instance.OnSwitchFrame_PostPress;
                @SwitchFrame_PostPress.canceled -= instance.OnSwitchFrame_PostPress;
                @KeyCom.started -= instance.OnKeyCom;
                @KeyCom.performed -= instance.OnKeyCom;
                @KeyCom.canceled -= instance.OnKeyCom;
                @Rotate.started -= instance.OnRotate;
                @Rotate.performed -= instance.OnRotate;
                @Rotate.canceled -= instance.OnRotate;
                @ChangeHeight.started -= instance.OnChangeHeight;
                @ChangeHeight.performed -= instance.OnChangeHeight;
                @ChangeHeight.canceled -= instance.OnChangeHeight;
                @ChangeStyle.started -= instance.OnChangeStyle;
                @ChangeStyle.performed -= instance.OnChangeStyle;
                @ChangeStyle.canceled -= instance.OnChangeStyle;
            }

            public void RemoveCallbacks(IBuildPlaceModeActions instance)
            {
                if (m_Wrapper.m_BuildPlaceModeActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IBuildPlaceModeActions instance)
            {
                foreach (var item in m_Wrapper.m_BuildPlaceModeActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_BuildPlaceModeActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public BuildPlaceModeActions @BuildPlaceMode => new BuildPlaceModeActions(this);
        public interface IBuildActions
        {
            void OnMoveBuild(InputAction.CallbackContext context);
            void OnDestroyBuild(InputAction.CallbackContext context);
            void OnChangeOutLook(InputAction.CallbackContext context);
            void OnChangeInteractiveActor(InputAction.CallbackContext context);
            void OnSelectBuild(InputAction.CallbackContext context);
            void OnKeyCom(InputAction.CallbackContext context);
        }
        public interface IBuildKeyComActions
        {
            void OnKeyCom(InputAction.CallbackContext context);
            void OnCopyBuild(InputAction.CallbackContext context);
            void OnPasteOutLook(InputAction.CallbackContext context);
            void OnCopyOutLook(InputAction.CallbackContext context);
        }
        public interface IBuildSelectionActions
        {
            void OnAlternativeType(InputAction.CallbackContext context);
            void OnAlterCategory(InputAction.CallbackContext context);
            void OnChangeFurnitureDisplay(InputAction.CallbackContext context);
            void OnSwichBtn(InputAction.CallbackContext context);
        }
        public interface IBuildingAppearanceActions
        {
            void OnAlterMaterial(InputAction.CallbackContext context);
        }
        public interface IBuildPlaceModeActions
        {
            void OnChangeActiveSocket(InputAction.CallbackContext context);
            void OnChangeOutLook(InputAction.CallbackContext context);
            void OnSwitchFrame_PreHold(InputAction.CallbackContext context);
            void OnSwitchFrame_PostPress(InputAction.CallbackContext context);
            void OnKeyCom(InputAction.CallbackContext context);
            void OnRotate(InputAction.CallbackContext context);
            void OnChangeHeight(InputAction.CallbackContext context);
            void OnChangeStyle(InputAction.CallbackContext context);
        }
    }
}
