using Sirenix.OdinInspector;

namespace ML.Engine.BuildingSystem.BuildingSocket
{
	[System.Serializable]
	public enum BuildingSocketType
	{
		[LabelText("None")]
		None,
		[LabelText("生命导流桩吸附点")]
		LifeDiversion,
		[LabelText("功能建筑吸附点")]
		PronodeAndInteract,
		[LabelText("地板表层A")]
		Floorsurface_A,
		[LabelText("墙面A")]
		Wallsurface_A,
		[LabelText("天花板A")]
		Ceiling_A,
		[LabelText("地板中心吸附点A")]
		Floor_Base_Center_A,
		[LabelText("被动地板连接")]
		Floor_Base,
		[LabelText("标准高墙A")]
		Wall_Base_A,
		[LabelText("高方墙连接")]
		Wall_Base,
		[LabelText("矮方墙A")]
		Wall_Base_1A,
		[LabelText("矮方墙连接")]
		Wall_Base1,
		[LabelText("长墙A")]
		Wall_LB_A,
		[LabelText("矮长墙A")]
		Wall_LB_1A,
		[LabelText("弧墙A")]
		Wall_Qua_A,
		[LabelText("矮弧墙A")]
		Wall_Qua_1A,
		[LabelText("长地板连接")]
		Floor_Lbase,
		[LabelText("弧地板连接")]
		Floor_Qua,
		[LabelText("高弧墙连接")]
		Wall_Qua,
		[LabelText("矮弧墙连接")]
		Wall_Qua1,
		[LabelText("长柱A")]
		Pillar_A,
		[LabelText("短柱A")]
		Pillar_A1,
		[LabelText("长柱C")]
		Pillar,
		[LabelText("短柱C")]
		Pillar1,
		[LabelText("标准屋顶A")]
		Roof_Base_A,
		[LabelText("矮标准屋顶A")]
		Roof_Base_A1,
		[LabelText("标准屋顶C")]
		Roof_Base,
		[LabelText("矮标准屋顶C")]
		Roof_Base1,
		[LabelText("地板角点C")]
		Floor_p_C,
	}
}
